<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HuaJiBot.NET\HuaJiBot.NET.csproj" />
    <ProjectReference Include="..\HuaJiBot.NET.AI\HuaJiBot.NET.AI.csproj" />
    <ProjectReference Include="..\HuaJiBot.NET.SourceGenerator\HuaJiBot.NET.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="HuaJiBot.NET.UnitTest" />
  </ItemGroup>
</Project>