use_default_settings:
  engines:
    keep_only:
      - brave
      - sogou
      - google cse

search:
  formats:
    - html
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false

outgoing:
  request_timeout: 4.0
  max_request_timeout: 6.0

engines:
  - name: brave
    timeout: 4.0
    weight: 2
  - name: google cse
    timeout: 4.0
    weight: 2
  - name: sogou
    timeout: 3.0
    weight: 1
